export enum ETableNames {
    products = 'products',
    sales = 'sales',
    saleDetails = 'sale_details',
    fincashs = 'fincashs',
    cashOutflows = 'cash_outflows',
    stocks = 'stocks',
    groups = 'groups',
    product_groups = 'product_groups',
    validities = 'validities',
    users = 'users',
    suppliers = 'suppliers',
    prod_output = 'prod_output',
    payments = 'payments',
    purchases = 'purchases',
    purchase_details = 'purchase_details',
    packs = 'packs',
    prod_packs = 'prod_packs',
    supplier_prod_map = 'supplier_prod_map',
    nf_emitters = 'nf_emitters',
}